# Generated by Django 5.2.1 on 2026-06-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='waitlist_position',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='候补序号'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('cancelled', '已取消'), ('waitlist', '候补中')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
